In [60]:
import pandas as pd
import numpy as np 
import matplotlib.pyplot as plt
import seaborn as sns
import csv
import requests

In [61]:
df = pd.read_csv('../data/full_data/libros_completados_final.csv')
df

C:\Users\elena\AppData\Local\Temp\ipykernel_28456\2469390319.py:1: DtypeWarning: Columns (2,9,11,15,18) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv('../data/full_data/libros_completados_final.csv')

,bookId,title,series,author,rating,description,language,isbn,genres,characters,bookFormat,pages,publisher,publishDate,firstPublishDate,awards,numRatings,likedPercent,setting,coverImg
0,2767052-the-hunger-games,The Hunger Games,The Hunger Games #1,Suzanne Collins,4.33,WINNING MEANS FAME AND FORTUNE.LOSING MEANS CE...,English,9780439023481,"['Young Adult', 'Fiction', 'Dystopia', 'Fantas...","['Katniss Everdeen', 'Peeta Mellark', 'Cato (H...",Hardcover,374,Scholastic Press,09/14/08,NaN,['Locus Award Nominee for Best Young Adult Boo...,6376780.0,96.0,"['District 12, Panem', 'Capitol, Panem', 'Pane...",https://i.gr-assets.com/images/S/compressed.ph...
1,2.Harry_Potter_and_the_Order_of_the_Phoenix,Harry Potter and the Order of the Phoenix,Harry Potter #5,"J.K. Rowling, Mary GrandPré (Illustrator)",4.50,There is a door at the end of a silent corrido...,English,9780439358071,"['Fantasy', 'Young Adult', 'Fiction', 'Magic',...","['Sirius Black', 'Draco Malfoy', 'Ron Weasley'...",Paperback,870,Scholastic Inc.,09/28/04,06/21/03,['Bram Stoker Award for Works for Young Reader...,2507623.0,98.0,['Hogwarts School of Witchcraft and Wizardry (...,https://i.gr-assets.com/images/S/compressed.ph...
2,2657.To_Kill_a_Mockingbird,To Kill a Mockingbird,To Kill a Mockingbird,Harper Lee,4.28,The unforgettable novel of a childhood in a sl...,English,9780062369635,"['Classics', 'Fiction', 'Historical Fiction', ...","['Scout Finch', 'Atticus Finch', 'Jem Finch', ...",Paperback,324,Harper Perennial Modern Classics,05/23/06,07/11/60,"['Pulitzer Prize for Fiction (1961)', 'Audie A...",4501075.0,95.0,"['Maycomb, Alabama (United States)']",https://i.gr-assets.com/images/S/compressed.ph...
3,1885.Pride_and_Prejudice,Pride and Prejudice,NaN,"Jane Austen, Anna Quindlen (Introduction)",4.26,Alternate cover edition of ISBN 9780679783268S...,English,NaN,"['Classics', 'Fiction', 'Romance', 'Historical...","['Mr. Bennet', 'Mrs. Bennet', 'Jane Bennet', '...",Paperback,279,Modern Library,10/10/00,01/28/13,[],2998241.0,94.0,"['United Kingdom', 'Derbyshire, England (Unite...",https://i.gr-assets.com/images/S/compressed.ph...
4,41865.Twilight,Twilight,The Twilight Saga #1,Stephenie Meyer,3.60,About three things I was absolutely positive.\...,English,9780316015844,"['Young Adult', 'Fantasy', 'Romance', 'Vampire...","['Edward Cullen', 'Jacob Black', 'Laurent', 'R...",Paperback,501,"Little, Brown and Company",09/06/06,10/05/05,"['Georgia Peach Book Award (2007)', 'Buxtehude...",4964519.0,78.0,"['Forks, Washington (United States)', 'Phoenix...",https://i.gr-assets.com/images/S/compressed.ph...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
74784,SzxlzgEACAAJ,Afterimage Slow Motion,NaN,Jyanome,NaN,NaN,en,3964335037,nan - yaoi,NaN,nan - nan,224.0,NaN,2021-12-02,2021-12-02,NaN,NaN,NaN,NaN,NaN
74785,Te04EQAAQBAJ,When Fate Holds Its Breath,NaN,Takiba,NaN,NaN,de,9783551624680,Comics & Graphic Novels - yaoi,NaN,nan - nan,29.0,NaN,2025,2025,NaN,NaN,NaN,NaN,http://books.google.com/books/content?id=6MsAE...
74786,s_8_EAAAQBAJ,Midnight Delivery Sex,NaN,Neneko Narazaki,NaN,Mit SNS-Card zum Sammeln in der ersten Auflage...,de,9783551620668,Comics & Graphic Novels - yaoi,NaN,nan - nan,29.0,Hayabusa,2021-05-04,2021-05-04,NaN,NaN,NaN,NaN,http://books.google.com/books/content?id=s_8_E...
74787,_yjnEAAAQBAJ,Monster Girl: 2,NaN,Kazuki Funatsu,NaN,"Dopo il loro incontro, Yatsuki si ritrova ad a...",it,9788834915899,Comics & Graphic Novels - isekai comedy,NaN,nan - nan,216.0,Edizioni BD,2020-05-01,2020-05-01,NaN,NaN,NaN,NaN,http://books.google.com/books/content?id=_yjnE...
74788,bjZVEAAAQBAJ,La saison du soleil,NaN,Shintaro Ishihara,NaN,"Lauréat du prestigieux prix Akutagawa en 1955,...",fr,9782714497598,Literary Collections - isekai space opera,NaN,nan - nan,131.0,Belfond,2022-01-27,2022-01-27,NaN,NaN,NaN,NaN,http://books.google.com/books/content?id=bjZVE...

In [62]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 74789 entries, 0 to 74788
Data columns (total 20 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   bookId            74789 non-null  object
 1   title             74789 non-null  object
 2   series            23470 non-null  object
 3   author            74517 non-null  object
 4   rating            53830 non-null  float64
 5   description       71379 non-null  object
 6   language          73542 non-null  object
 7   isbn              74028 non-null  object
 8   genres            74789 non-null  object
 9   characters        52478 non-null  object
 10  bookFormat        73316 non-null  object
 11  pages             73162 non-null  object
 12  publisher         66657 non-null  object
 13  publishDate       74420 non-null  object
 14  firstPublishDate  53463 non-null  object
 15  awards            52478 non-null  object
 16  numRatings        53830 non-null  float64
 17  likedPercent      51856 non-null  float64
 18  setting           52478 non-null  object
 19  coverImg          71750 non-null  object
dtypes: float64(3), object(17)
memory usage: 11.4+ MB

Aplicamos sobre todo el dataframe los nulos para que los identifiqque

In [63]:
df.replace(
    ['NaN', 'nan', 'None', 'NULL', 'null', 'nan - nan', '', '[]', ' '], 
    np.nan, 
    inplace=True
)

ISBN
Borramos la columna de isbn porque si que nos ha servido para encontrar la información de los libros pero ya no aporta nada

# ISBN

In [64]:
df = df.drop('isbn', axis=1)

Borramos también la columna de bookId porquetampoco nos va a servir de nada

# bookId

In [65]:
df = df.drop('bookId', axis=1)

# title y Author

título y autor
Miramos si hay duplicados

In [66]:
duplicados_titulo_autor = df[
    df.duplicated(subset=['title', 'author'], keep=False)
]

In [67]:
n_duplicados = duplicados_titulo_autor.groupby(['title', 'author']).size()
print(n_duplicados.sort_values(ascending=False).head(20))

title                                                                author
Sara Crewe; Or, What Happened at Miss Minchin's Boarding School      Burnett                                  9
Divine Life Ring System                                              Wu Mei Ren, Da Wan                       6
WIEDERGEBURT: Legend of the Reincarnated Warrior                     Brandon Varnell                          6
The Ultimate Celestial Martial Emperor                               de Yun Piao Dang                         5
The Godslaying Tower                                                 Nangong Yuan Jing                        5
Isekai                                                               George Alfaro                            5
Limits of Destiny                                                    Sharlyn G. Branson (Goodreads Author)    5
My Next Life as a Villainess: All Routes Lead to Doom!               Satoru Yamaguchi                         4
HELP! I Got Sucked Into My Boyfriend's Fantasy Dungeons Fanfiction!  Minnie Rider                             4
Holiday Romance                                                      Charles Dickens                          4
I'm in love with the villainess                                      Inori                                    4
The Year's Best Dark Fantasy & Horror                                Paula Guran                              4
Through My Window                                                    Ariana Godoy                             4
Averno                                                               Louise Glück                             4
Another World: Romantic Devil King                                   Xin SuiMengHan                           4
Mexican Gothic                                                       Silvia Moreno-Garcia                     4
The Good Person Reward System                                        Sima Tiao Liu Yi                         4
1984                                                                 George Orwell                            4
Narrative Retellings                                                 Marina Lambrou                           3
The Way of Kings                                                     Brandon Sanderson (Goodreads Author)     3
dtype: int64

In [68]:
df.loc[df['author'] == 'Burnett']

,title,series,author,rating,description,language,genres,characters,bookFormat,pages,publisher,publishDate,firstPublishDate,awards,numRatings,likedPercent,setting,coverImg
56619,"Sara Crewe; Or, What Happened at Miss Minchin'...",NaN,Burnett,NaN,"Sara Crewe; Or, What Happened at Miss Minchin'...",en,nan - boarding school fiction,NaN,NaN,46.0,NaN,2020-11-18,2020-11-18,NaN,NaN,NaN,NaN,http://books.google.com/books/content?id=Q_QLz...
58713,"Sara Crewe; Or, What Happened at Miss Minchin'...",NaN,Burnett,NaN,"Sara Crewe; Or, What Happened at Miss Minchin'...",en,nan - boarding school fiction,NaN,NaN,44.0,NaN,2021-05-09,2021-05-09,NaN,NaN,NaN,NaN,http://books.google.com/books/content?id=Q_QLz...
59191,"Sara Crewe; Or, What Happened at Miss Minchin'...",NaN,Burnett,NaN,"Sara Crewe; Or, What Happened at Miss Minchin'...",en,nan - boarding school fiction,NaN,NaN,46.0,Independently Published,2020-11-28,2020-11-28,NaN,NaN,NaN,NaN,http://books.google.com/books/content?id=k8oMz...
59192,"Sara Crewe; Or, What Happened at Miss Minchin'...",NaN,Burnett,NaN,"Sara Crewe; Or, What Happened at Miss Minchin'...",en,nan - boarding school fiction,NaN,NaN,46.0,Independently Published,2020-11-20,2020-11-20,NaN,NaN,NaN,NaN,http://books.google.com/books/content?id=Q_QLz...
59195,"Sara Crewe; Or, What Happened at Miss Minchin'...",NaN,Burnett,NaN,"Sara Crewe; Or, What Happened at Miss Minchin'...",en,nan - boarding school fiction,NaN,NaN,46.0,NaN,2020-11-17,2020-11-17,NaN,NaN,NaN,NaN,http://books.google.com/books/content?id=Q_QLz...
59196,"Sara Crewe; Or, What Happened at Miss Minchin'...",NaN,Burnett,NaN,"Sara Crewe; Or, What Happened at Miss Minchin'...",en,nan - boarding school fiction,NaN,NaN,46.0,NaN,2020-11-15,2020-11-15,NaN,NaN,NaN,NaN,http://books.google.com/books/content?id=Q_QLz...
59197,"Sara Crewe; Or, What Happened at Miss Minchin'...",NaN,Burnett,NaN,"Sara Crewe; Or, What Happened at Miss Minchin'...",en,nan - boarding school fiction,NaN,NaN,46.0,NaN,2021-02-10,2021-02-10,NaN,NaN,NaN,NaN,http://books.google.com/books/content?id=Q_QLz...
59198,"Sara Crewe; Or, What Happened at Miss Minchin'...",NaN,Burnett,NaN,"Sara Crewe; Or, What Happened at Miss Minchin'...",en,nan - boarding school fiction,NaN,NaN,46.0,Independently Published,2020-11-14,2020-11-14,NaN,NaN,NaN,NaN,http://books.google.com/books/content?id=k8oMz...
60511,"Sara Crewe; Or, What Happened at Miss Minchin'...",NaN,Burnett,NaN,"Sara Crewe; Or, What Happened at Miss Minchin'...",en,nan - boarding school fiction,NaN,NaN,46.0,NaN,2020-11-16,2020-11-16,NaN,NaN,NaN,NaN,http://books.google.com/books/content?id=H2lbQ...

Nos quedamos con el que está en el índice 2 porque tiene más información, los demás están repetidos

In [69]:
df = df.loc[(df['author'] != 'Burnett') | (df.index == 2)]

In [70]:
df.loc[df['title'] == 'Divine Life Ring System']

,title,series,author,rating,description,language,genres,characters,bookFormat,pages,publisher,publishDate,firstPublishDate,awards,numRatings,likedPercent,setting,coverImg
66944,Divine Life Ring System,NaN,"Da Wan, Wu Mei Ren",NaN,Niu Li was just an ordinary high school studen...,en,Fiction - isekai high fantasy,NaN,NaN,0.0,Da WAN,2024-03,2024-03,NaN,NaN,NaN,NaN,http://books.google.com/books/content?id=0XxyC...
66945,Divine Life Ring System,NaN,Wu Mei Ren,NaN,Niu Li was just an ordinary high school studen...,en,Fiction - isekai high fantasy,NaN,NaN,0.0,Da WAN,2024-03,2024-03,NaN,NaN,NaN,NaN,http://books.google.com/books/content?id=0XxyC...
66950,Divine Life Ring System,NaN,"Wu Mei Ren, Da Wan",NaN,Niu Li was just an ordinary high school studen...,en,Fiction - isekai high fantasy,NaN,NaN,0.0,Da WAN,2024-03-17,2024-03-17,NaN,NaN,NaN,NaN,http://books.google.com/books/content?id=0XxyC...
67378,Divine Life Ring System,NaN,"Wu Mei Ren, Da Wan",NaN,Niu Li was just an ordinary high school studen...,en,Fiction - isekai high fantasy,NaN,NaN,0.0,Da WAN,2024-03-17,2024-03-17,NaN,NaN,NaN,NaN,http://books.google.com/books/content?id=VYaRe...
67380,Divine Life Ring System,NaN,Wu Mei Ren,NaN,Niu Li was just an ordinary high school studen...,en,Fiction - isekai high fantasy,NaN,NaN,0.0,Da WAN,2024-03-16,2024-03-16,NaN,NaN,NaN,NaN,http://books.google.com/books/content?id=VYaRe...
67596,Divine Life Ring System,NaN,"Wu Mei Ren, Da Wan",NaN,Niu Li was just an ordinary high school studen...,en,Fiction - isekai dark fantasy,NaN,NaN,0.0,Da WAN,2024-03-17,2024-03-17,NaN,NaN,NaN,NaN,http://books.google.com/books/content?id=0XxyC...
67598,Divine Life Ring System,NaN,"Wu Mei Ren, Da Wan",NaN,Niu Li was just an ordinary high school studen...,en,Fiction - isekai dark fantasy,NaN,NaN,0.0,Da WAN,2024-03-17,2024-03-17,NaN,NaN,NaN,NaN,http://books.google.com/books/content?id=VYaRe...
67601,Divine Life Ring System,NaN,"Wu Mei Ren, Da Wan",NaN,Niu Li was just an ordinary high school studen...,en,Fiction - isekai dark fantasy,NaN,NaN,0.0,Da WAN,2024-03-17,2024-03-17,NaN,NaN,NaN,NaN,http://books.google.com/books/content?id=0XxyC...
67934,Divine Life Ring System,NaN,"Wu Mei Ren, Da Wan",NaN,Niu Li was just an ordinary high school studen...,en,Fiction - isekai dark fantasy,NaN,NaN,0.0,Da WAN,2024-03-17,2024-03-17,NaN,NaN,NaN,NaN,http://books.google.com/books/content?id=f7Gvs...

Estos están duplicados, así que nos quedamos con uno

In [71]:
df = df.loc[(df['title'] != 'Divine Life Ring System') | (df.duplicated(subset='title') == False)]

In [72]:
df.loc[df['title'] == 'WIEDERGEBURT: Legend of the Reincarnated Warrior']

,title,series,author,rating,description,language,genres,characters,bookFormat,pages,publisher,publishDate,firstPublishDate,awards,numRatings,likedPercent,setting,coverImg
54609,WIEDERGEBURT: Legend of the Reincarnated Warrior,NaN,Brandon Varnell,NaN,"THE BATTLE IS WON Eryk, Kari, Fay, and Lin are...",en,Young Adult Fiction - gamelit,NaN,NaN,282.0,Kitsune Incorporated,2022-04-26,2022-04-26,NaN,NaN,NaN,NaN,http://books.google.com/books/content?id=vj_9E...
54612,WIEDERGEBURT: Legend of the Reincarnated Warrior,NaN,Brandon Varnell,NaN,THE BATTLE IS WON Eryk travels with Herleif As...,en,Comics & Graphic Novels - gamelit,NaN,NaN,265.0,Kitsune Incorporated,2022-07-19,2022-07-19,NaN,NaN,NaN,NaN,http://books.google.com/books/content?id=vj_9E...
54616,WIEDERGEBURT: Legend of the Reincarnated Warrior,NaN,Brandon Varnell,NaN,A CHANCE TO START OVER… Eryk's dreams continue...,en,Fiction - gamelit,NaN,NaN,224.0,Kitsune Incorporated,2020-01-28,2020-01-28,NaN,NaN,NaN,NaN,http://books.google.com/books/content?id=vj_9E...
56732,WIEDERGEBURT: Legend of the Reincarnated Warrior,NaN,Brandon Varnell,NaN,THE BATTLE IS NOT WON Eryk returns to Nevaria ...,en,Fiction - gamelit,NaN,NaN,276.0,Kitsune Incorporated,2022-10-25,2022-10-25,NaN,NaN,NaN,NaN,http://books.google.com/books/content?id=vj_9E...
56740,WIEDERGEBURT: Legend of the Reincarnated Warrior,NaN,Brandon Varnell,NaN,THE BATTLE IS FINALLY WON While the invading a...,en,Comics & Graphic Novels - gamelit,NaN,NaN,283.0,Kitsune Incorporated,2023-01-24,2023-01-24,NaN,NaN,NaN,NaN,http://books.google.com/books/content?id=vj_9E...
56758,WIEDERGEBURT: Legend of the Reincarnated Warrior,NaN,Brandon Varnell,NaN,A CHANCE TO START OVER… At the end of his life...,en,Fiction - gamelit,NaN,NaN,290.0,Kitsune Incorporated,2020-12-03,2020-12-03,NaN,NaN,NaN,NaN,http://books.google.com/books/content?id=vj_9E...

En este caso vemos que son libros diferentes de una misma saga, por eso lo que hacemos es ponerle el nombre de serie y al título ponerle número de cada serie

In [73]:
mask = df['title'] == 'WIEDERGEBURT: Legend of the Reincarnated Warrior'
df.loc[mask, 'series'] = 'WIEDERGEBURT: Legend of the Reincarnated Warrior'
df.loc[mask, 'title'] = [
    f"WIEDERGEBURT: Legend of the Reincarnated Warrior {i+1}" for i in range(mask.sum())
]

In [74]:
df.loc[df['title'] == 'The Ultimate Celestial Martial Emperor']

,title,series,author,rating,description,language,genres,characters,bookFormat,pages,publisher,publishDate,firstPublishDate,awards,numRatings,likedPercent,setting,coverImg
55042,The Ultimate Celestial Martial Emperor,NaN,de Yun Piao Dang,NaN,"Jiang Yuan, an ordinary person from Earth, fin...",en,Fiction - isekai fantasy,NaN,NaN,0.0,He Qiao Qiao,2024-04-12,2024-04-12,NaN,NaN,NaN,NaN,http://books.google.com/books/content?id=KSLK0...
67770,The Ultimate Celestial Martial Emperor,NaN,de Yun Piao Dang,NaN,NaN,en,nan - isekai urban fantasy,NaN,NaN,0.0,Ultimate Celestial Martial Emperor,2024-04-12,2024-04-12,NaN,NaN,NaN,NaN,http://books.google.com/books/content?id=KSLK0...
67784,The Ultimate Celestial Martial Emperor,NaN,de Yun Piao Dang,NaN,NaN,en,nan - isekai mystery,NaN,NaN,0.0,Ultimate Celestial Martial Emperor,2024-04-12,2024-04-12,NaN,NaN,NaN,NaN,http://books.google.com/books/content?id=KSLK0...
69260,The Ultimate Celestial Martial Emperor,NaN,de Yun Piao Dang,NaN,"Jiang Yuan, an ordinary person from Earth, fin...",en,Fiction - isekai urban fantasy,NaN,NaN,0.0,He Qiao Qiao,2024-03-09,2024-03-09,NaN,NaN,NaN,NaN,http://books.google.com/books/content?id=KSLK0...
71216,The Ultimate Celestial Martial Emperor,NaN,de Yun Piao Dang,NaN,"Jiang Yuan, an ordinary person from Earth, fin...",en,Fiction - isekai fantasy adventure,NaN,NaN,0.0,He Qiao Qiao,2024-04-12,2024-04-12,NaN,NaN,NaN,NaN,http://books.google.com/books/content?id=KSLK0...

En este caso nos quedamos con uno porque están duplicados

In [75]:
df = df.loc[(df['title'] != 'The Ultimate Celestial Martial Emperor') | (df.duplicated(subset='title') == False)]

In [76]:
df.loc[df['title'] == 'The Godslaying Tower']

,title,series,author,rating,description,language,genres,characters,bookFormat,pages,publisher,publishDate,firstPublishDate,awards,numRatings,likedPercent,setting,coverImg
58267,The Godslaying Tower,NaN,Nangong Yuan Jing,NaN,Demons from beyond suddenly invaded the realm ...,en,Fiction - isekai adventure,NaN,NaN,0.0,Zhou Yan,2024-04-05,2024-04-05,NaN,NaN,NaN,NaN,http://books.google.com/books/content?id=sny10...
66799,The Godslaying Tower,NaN,Nangong Yuan Jing,NaN,Demons from beyond suddenly invaded the realm ...,en,Fiction - isekai fantasy adventure,NaN,NaN,0.0,Zhou Yan,2024-04-05,2024-04-05,NaN,NaN,NaN,NaN,http://books.google.com/books/content?id=sny10...
66813,The Godslaying Tower,NaN,Nangong Yuan Jing,NaN,Demons from beyond suddenly invaded the realm ...,en,Fiction - isekai adventure,NaN,NaN,0.0,Zhou Yan,2024-04-05,2024-04-05,NaN,NaN,NaN,NaN,http://books.google.com/books/content?id=sny10...
68287,The Godslaying Tower,NaN,Nangong Yuan Jing,NaN,Demons from beyond suddenly invaded the realm ...,en,Fiction - isekai fantasy adventure,NaN,NaN,0.0,Zhou Yan,2024-04-05,2024-04-05,NaN,NaN,NaN,NaN,http://books.google.com/books/content?id=sny10...
70585,The Godslaying Tower,NaN,Nangong Yuan Jing,NaN,Demons from beyond suddenly invaded the realm ...,en,Fiction - isekai dark fantasy,NaN,NaN,0.0,Zhou Yan,2024-04-05,2024-04-05,NaN,NaN,NaN,NaN,http://books.google.com/books/content?id=sny10...

Nos quedamos con uno porque están duplicados

In [77]:
df = df.loc[(df['title'] != 'The Godslaying Tower') | (df.duplicated(subset='title') == False)]

In [78]:
df.loc[df['title'] == 'Isekai']

,title,series,author,rating,description,language,genres,characters,bookFormat,pages,publisher,publishDate,firstPublishDate,awards,numRatings,likedPercent,setting,coverImg
53824,Isekai,NaN,"Jorge Boris, Rolando Peralta",NaN,Isekai The Adventure is Book about adventure L...,en,Comics & Graphic Novels - isekai romance,NaN,NaN,0.0,NaN,2023-12-13,2023-12-13,NaN,NaN,NaN,NaN,http://books.google.com/books/content?id=YCRXE...
53848,Isekai,NaN,George Alfaro,NaN,"""Si tuviera el poder para cambiar al mundo... ...",es,nan - isekai romance,NaN,NaN,224.0,Independently Published,2021-05-05,2021-05-05,NaN,NaN,NaN,NaN,http://books.google.com/books/content?id=YCRXE...
58263,Isekai,NaN,Yenmigael 77 7,NaN,Immerse yourself in a captivating world of mag...,en,Fiction - isekai adventure,NaN,NaN,0.0,Independently Published,2025-02-17,2025-02-17,NaN,NaN,NaN,NaN,http://books.google.com/books/content?id=YCRXE...
62999,Isekai,NaN,Gabriel Antonio Ramirez,NaN,What if a simple medallion didn't just transpo...,en,Young Adult Fiction - isekai fantasy,NaN,NaN,0.0,Independently Published,2025-02-09,2025-02-09,NaN,NaN,NaN,NaN,http://books.google.com/books/content?id=XsSoE...
65445,Isekai,NaN,M Jean-Louis VILL,NaN,Arius Lovelace is no ordinary baron. He is the...,en,Fiction - isekai action,NaN,NaN,0.0,NaN,2024-11-26,2024-11-26,NaN,NaN,NaN,NaN,http://books.google.com/books/content?id=XsSoE...
65513,Isekai,NaN,George Alfaro,NaN,La guerra entre el Reino de Etrica y el Reino ...,es,nan - isekai mystery,NaN,NaN,0.0,Independently Published,2023-11-27,2023-11-27,NaN,NaN,NaN,NaN,http://books.google.com/books/content?id=XsSoE...
65534,Isekai,NaN,George Alfaro,NaN,Luego de la tragedia personal que nuestro prot...,es,nan - isekai magical realism,NaN,NaN,174.0,Independently Published,2021-09-19,2021-09-19,NaN,NaN,NaN,NaN,http://books.google.com/books/content?id=XsSoE...
65557,Isekai,NaN,George Alfaro,NaN,Los años han pasado y la coronación está a la ...,es,nan - isekai dystopian,NaN,NaN,0.0,Independently Published,2022-05-31,2022-05-31,NaN,NaN,NaN,NaN,http://books.google.com/books/content?id=XsSoE...
66739,Isekai,NaN,George Alfaro,NaN,¡Guerra! Las negociaciones fallaron y ahora la...,es,nan - isekai dark fantasy,NaN,NaN,0.0,Independently Published,2023-02-05,2023-02-05,NaN,NaN,NaN,NaN,http://books.google.com/books/content?id=XsSoE...
67159,Isekai,NaN,M Jean-Louis VILL,NaN,Arius Lovelace is no ordinary baron. He is the...,en,Fiction - isekai horror,NaN,NaN,0.0,NaN,2024-11-26,2024-11-26,NaN,NaN,NaN,NaN,http://books.google.com/books/content?id=XsSoE...
68427,Isekai,NaN,Yenmigael 7 77,NaN,"Tauchen Sie mit The Path of the Fang, dem erst...",de,Fiction - isekai thriller,NaN,NaN,0.0,Independently Published,2025-02-27,2025-02-27,NaN,NaN,NaN,NaN,http://books.google.com/books/content?id=XsSoE...

A los libros de George Alfaro les añadimos un número como serie y le añadimos las serie

In [79]:
mask = (df['title'] == 'Isekai') & (df['author'] == 'George Alfaro')
df.loc[mask, 'series'] = 'Isekai'
df.loc[mask, 'title'] = [
    f'Isekai {i+1}' for i in range(mask.sum())
]

In [80]:
df.loc[df['title'] == 'Isekai']

,title,series,author,rating,description,language,genres,characters,bookFormat,pages,publisher,publishDate,firstPublishDate,awards,numRatings,likedPercent,setting,coverImg
53824,Isekai,NaN,"Jorge Boris, Rolando Peralta",NaN,Isekai The Adventure is Book about adventure L...,en,Comics & Graphic Novels - isekai romance,NaN,NaN,0.0,NaN,2023-12-13,2023-12-13,NaN,NaN,NaN,NaN,http://books.google.com/books/content?id=YCRXE...
58263,Isekai,NaN,Yenmigael 77 7,NaN,Immerse yourself in a captivating world of mag...,en,Fiction - isekai adventure,NaN,NaN,0.0,Independently Published,2025-02-17,2025-02-17,NaN,NaN,NaN,NaN,http://books.google.com/books/content?id=YCRXE...
62999,Isekai,NaN,Gabriel Antonio Ramirez,NaN,What if a simple medallion didn't just transpo...,en,Young Adult Fiction - isekai fantasy,NaN,NaN,0.0,Independently Published,2025-02-09,2025-02-09,NaN,NaN,NaN,NaN,http://books.google.com/books/content?id=XsSoE...
65445,Isekai,NaN,M Jean-Louis VILL,NaN,Arius Lovelace is no ordinary baron. He is the...,en,Fiction - isekai action,NaN,NaN,0.0,NaN,2024-11-26,2024-11-26,NaN,NaN,NaN,NaN,http://books.google.com/books/content?id=XsSoE...
67159,Isekai,NaN,M Jean-Louis VILL,NaN,Arius Lovelace is no ordinary baron. He is the...,en,Fiction - isekai horror,NaN,NaN,0.0,NaN,2024-11-26,2024-11-26,NaN,NaN,NaN,NaN,http://books.google.com/books/content?id=XsSoE...
68427,Isekai,NaN,Yenmigael 7 77,NaN,"Tauchen Sie mit The Path of the Fang, dem erst...",de,Fiction - isekai thriller,NaN,NaN,0.0,Independently Published,2025-02-27,2025-02-27,NaN,NaN,NaN,NaN,http://books.google.com/books/content?id=XsSoE...

Del autor M Jean-Louis Vill están duplicados así que nos quedamos con uno

In [81]:
# Filtrar los duplicados específicos
mask = (df['title'] == 'Isekai') & (df['author'] == 'M Jean-Louis VILL')
indexes_to_drop = df[mask].index[1:] 
df = df.drop(indexes_to_drop)

In [82]:
df[df['title'].duplicated()]

,title,series,author,rating,description,language,genres,characters,bookFormat,pages,publisher,publishDate,firstPublishDate,awards,numRatings,likedPercent,setting,coverImg
664,Inferno,Robert Langdon #4,Dan Brown (Goodreads Author),3.85,Harvard professor of symbology Robert Langdon ...,English,"['Fiction', 'Thriller', 'Mystery', 'Mystery Th...","['Robert Langdon', 'Sienna Brooks', 'Laurence ...",Hardcover,463,Doubleday,05/14/13,NaN,['Goodreads Choice Award for Mystery & Thrille...,469149.0,91.0,"['Istanbul (Turkey)', 'Florence (Italy)', 'Ven...",https://i.gr-assets.com/images/S/compressed.ph...
768,The Awakening,Darkest Powers #2,Kelley Armstrong (Goodreads Author),4.14,"If you had met me a few weeks ago, you probabl...",English,"['Young Adult', 'Fantasy', 'Paranormal', 'Urba...","['Chloe Saunders', 'Derek Souza', ""Victoria 'T...",Hardcover,360,HarperCollins,04/28/09,NaN,"[""Romantic Times Reviewers' Choice Award (RT A...",107557.0,95.0,"['Buffalo, New York (United States)']",https://i.gr-assets.com/images/S/compressed.ph...
913,Into the Wild,Warriors #1,Erin Hunter,4.30,"For generations, four Clans of wild cats have ...",English,"['Fantasy', 'Animals', 'Fiction', 'Young Adult...","['Lionheart', 'Graystripe', 'Fireheart', 'Blue...",Paperback,288,HarperTrophy,January 6th 2004,01/09/03,NaN,75782.0,95.0,"['The Forest', 'Fourtrees']",https://i.gr-assets.com/images/S/compressed.ph...
1210,Burned,Burned #1,Ellen Hopkins (Goodreads Author),4.25,I do know things really began to spin out of c...,English,"['Young Adult', 'Poetry', 'Fiction', 'Contempo...","['Ethan', 'Pattyn Von Stratten']",Hardcover,431,Margaret K. McElderry Books,April 1st 2006,03/28/06,NaN,57383.0,94.0,['Nevada (United States)'],https://i.gr-assets.com/images/S/compressed.ph...
1387,North and South,North and South #1,John Jakes,4.20,"Part history, part novel, this book chronicles...",English,"['Historical Fiction', 'Fiction', 'Historical'...","['George Hazard', 'Orry Main']",Paperback,812,Signet,June 1st 2000,10/28/82,NaN,56771.0,96.0,['United States of America'],https://i.gr-assets.com/images/S/compressed.ph...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
74711,Writing Memoir (Lit Starts),NaN,San Francisco San Francisco Writers' Grotto,NaN,A fill-in book from the San Francisco Writers'...,en,nan - memoir,NaN,NaN,96.0,Abrams Noterie,2020-02-11,2020-02-11,NaN,NaN,NaN,NaN,http://books.google.com/books/content?id=MEhzE...
74718,Turtle in Paradise,NaN,"Jennifer L. Holm, Savanna Ganucheau",4.00,"A graphic novel adaptation of the beloved, bes...",en,Juvenile Fiction - graphic novels,NaN,NaN,0.0,National Geographic Books,2021-06-29,2021-06-29,NaN,1.0,NaN,NaN,http://books.google.com/books/content?id=JdoDE...
74728,The Blue Poetry Book Annotated,NaN,Andrew Lang,NaN,The Blue Poetry Book was the third of the seri...,en,nan - poetry,NaN,NaN,541.0,NaN,2020-04-28,2020-04-28,NaN,NaN,NaN,NaN,NaN
74737,"In Other Words, Love",NaN,Shirley Jump,NaN,She’s been hired to ghostwrite a CEO’s autobio...,en,Fiction - second chance romance,NaN,NaN,0.0,Hallmark Publishing,2020-04-21,2020-04-21,NaN,NaN,NaN,NaN,http://books.google.com/books/content?id=J1YAE...
74752,Lost in the Dark,NaN,Brad Weismann,NaN,Two horror films were nominated for the Academ...,en,Performing Arts - zombies horror,NaN,NaN,257.0,Univ. Press of Mississippi,2021-04-22,2021-04-22,NaN,NaN,NaN,NaN,http://books.google.com/books/content?id=snNUD...

In [83]:
df.loc[df['title'] == 'Limits of Destiny']

,title,series,author,rating,description,language,genres,characters,bookFormat,pages,publisher,publishDate,firstPublishDate,awards,numRatings,likedPercent,setting,coverImg
11841,Limits of Destiny,Limits of Destiny #1,Sharlyn G. Branson (Goodreads Author),3.86,Alexia Welson is very beautiful and men do not...,NaN,"['Romance', 'Erotica', 'Contemporary', 'Contem...",NaN,ebook,NaN,Smashwords Edition,August 30th 2015,07/10/15,NaN,497.0,87.0,['Switzerland'],https://i.gr-assets.com/images/S/compressed.ph...
12004,Limits of Destiny,Limits of Destiny #5,Sharlyn G. Branson (Goodreads Author),4.50,Does love have the power to overcome all obsta...,English,['Erotica'] - nan,NaN,Kindle Edition,260,Sharlyn G. Branson,March 31st 2016,NaN,NaN,114.0,96.0,NaN,https://i.gr-assets.com/images/S/compressed.ph...
12180,Limits of Destiny,Limits of Destiny #2,Sharlyn G. Branson (Goodreads Author),4.32,The detonation of a bomb in Kraftberg’s hotel ...,English,"['Contemporary Romance', 'Romance', 'Adult Fic...",NaN,Kindle Edition,189,NaN,July 20th 2015,NaN,NaN,184.0,95.0,NaN,https://i.gr-assets.com/images/S/compressed.ph...
12498,Limits of Destiny,Limits of Destiny #3,Sharlyn G. Branson (Goodreads Author),4.38,"Back in Switzerland, Alexia is forced to face ...",English,"['Contemporary Romance', 'Romance'] - nan",NaN,Kindle Edition,314,Sharlyn G. Branson,August 17th 2015,NaN,NaN,156.0,96.0,NaN,https://i.gr-assets.com/images/S/compressed.ph...
12781,Limits of Destiny,Limits of Destiny #4,Sharlyn G. Branson (Goodreads Author),4.47,What are the thresholds of pain tolerance? Ale...,English,"['Romance', 'Contemporary Romance', 'Contempor...",NaN,Kindle Edition,179,Sharlyn G. Branson,October 15th 2015,NaN,NaN,150.0,96.0,NaN,https://i.gr-assets.com/images/S/compressed.ph...

En este caso, lo que vamos a hacer es pasar el numero de serie al titulo

In [84]:
mask = df['title'] == 'Limits of Destiny'
df.loc[mask, 'title'] = df.loc[mask].apply(
    lambda row: f"{row['title']} {row['series'].split('#')[-1].strip()}" if pd.notnull(row['series']) else row['title'],
    axis=1
)
df.loc[mask, 'series'] = 'Limits of Destiny'

In [85]:
duplicados_titulo_autor = df[
    df.duplicated(subset=['title', 'author'], keep=False)
]
n_duplicados = duplicados_titulo_autor.groupby(['title', 'author']).size()
print(n_duplicados.sort_values(ascending=False).head(20))

title                                                                author
My Next Life as a Villainess: All Routes Lead to Doom!               Satoru Yamaguchi                4
Another World: Romantic Devil King                                   Xin SuiMengHan                  4
Mexican Gothic                                                       Silvia Moreno-Garcia            4
I'm in love with the villainess                                      Inori                           4
Holiday Romance                                                      Charles Dickens                 4
HELP! I Got Sucked Into My Boyfriend's Fantasy Dungeons Fanfiction!  Minnie Rider                    4
The Year's Best Dark Fantasy & Horror                                Paula Guran                     4
Through My Window                                                    Ariana Godoy                    4
Averno                                                               Louise Glück                    4
The Good Person Reward System                                        Sima Tiao Liu Yi                4
1984                                                                 George Orwell                   4
Fandom Culture and The Archers                                       Cara Courage, Nicola Headlam    3
Love, Power, and Gender in Seventeenth-Century French Fairy Tales    Bronwyn Reddan                  3
CyberPunk                                                            Runtill sun                     3
Creswell Legacy                                                      Kylie Bellerose                 3
Crave                                                                Tracy Wolff                     3
The Summer of '98                                                    Tay Marley                      3
Legacy Academy                                                       M Guida                         3
Lost in the Dark                                                     Brad Weismann                   3
The Wall of Winnipeg and Me                                          Mariana Zapata                  3
dtype: int64

Miramos cuantos titulos y autores hay vacíos

In [86]:
df[['author', 'title']].isna().sum()

author    272
title       0
dtype: int64

Borramos los autores vacíos

In [87]:
df = df[df['author'].notna()]

# Series

Los libros independientes que no vienen de series, los cambiamos de no nulos a Standalone Novel

In [88]:
df['series'].fillna("Standalone Novel", inplace=True)
df['series']

0          The Hunger Games #1
1              Harry Potter #5
2        To Kill a Mockingbird
3             Standalone Novel
4         The Twilight Saga #1
                 ...
74784         Standalone Novel
74785         Standalone Novel
74786         Standalone Novel
74787         Standalone Novel
74788         Standalone Novel
Name: series, Length: 74491, dtype: object

# Description

Borramos las filas que están vacías

In [89]:
df['description'].isnull().sum()

3240

In [90]:
df = df.dropna(subset=['description'])

Miramos los libros en los que se duplica la descripción, el títutlo y el autor

In [91]:
duplicados_title_description = df[df.duplicated(subset=['title', 'description', 'author'], keep='first')]
duplicados_title_description

,title,series,author,rating,description,language,genres,characters,bookFormat,pages,publisher,publishDate,firstPublishDate,awards,numRatings,likedPercent,setting,coverImg
22515,Mute: Poems That Saved My Life!: Poems by Vidy...,Standalone Novel,Vidya Gargote,5.00,MUTE: Poems That Saved My Life! is an inspira...,en,[] - nan,NaN,Paperback,210,Balboa Press,October 21st 2014,NaN,NaN,1.0,100.0,NaN,http://books.google.com/books/content?id=zgRUB...
37431,Promises to Keep,Standalone Novel,Ann Tatlock,3.94,Eleven-year-old Roz (Rosalind) Anthony and her...,English,"['Fiction', 'Christian Fiction', 'Christian', ...",NaN,Paperback,348,Bethany House Publishers,February 1st 2011,01/01/11,NaN,1997.0,95.0,['Illinois (United States)'],https://i.gr-assets.com/images/S/compressed.ph...
37432,Click,Standalone Novel,"Eoin Colfer, Linda Sue Park, Ruth Ozeki (Goodr...",3.54,A video message from a dead person. A larcenou...,English,"['Young Adult', 'Fiction', 'Short Stories', 'M...",NaN,Unknown Binding,217,Not Avail,October 1st 2007,11/06/07,['Deutscher Jugendliteraturpreis Nominee for J...,1910.0,86.0,NaN,https://i.gr-assets.com/images/S/compressed.ph...
37433,Die Unendlichkeit schläft,Loki von Schallern Staffel 1 #3,Melanie Meier,4.50,"Überall, wo er hingeht, reißen Höllenfeuer all...",German,[] - nan,NaN,Kindle Edition,NaN,neobooks Self-Publishing,November 2014,NaN,NaN,2.0,NaN,NaN,https://i.gr-assets.com/images/S/compressed.ph...
37434,"Death Note: Black Edition, Vol. 2",Death Note: Black Edition #2,"Tsugumi Ohba, Takeshi Obata, Yuki Kowalsky (tr...",4.48,Intégrale regroupant les tomes 3 et 4Tome 3 :L...,German,"['Graphic Novels', 'Comics', 'Fantasy', 'Manga...","['Light Yagami', 'Ryuk']",Paperback,385,Tokyopop,2009,11/06/03,NaN,5849.0,99.0,NaN,https://i.gr-assets.com/images/S/compressed.ph...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
74532,The Big Book of Cyberpunk,Standalone Novel,Jared Shurin,NaN,A genre-defining—and redefining—collection of ...,en,Fiction - cyberpunk,NaN,NaN,1137.0,Vintage,2023-09-26,2023-09-26,NaN,NaN,NaN,NaN,http://books.google.com/books/content?id=R2y1E...
74643,The Scum Villain's Self-Saving System: Ren Zha...,Standalone Novel,Mo Xiang Tong Xiu,4.50,NEW YORK TIMES BEST SELLER! The blockbuster da...,en,Fiction - danmei,NaN,NaN,0.0,Seven Seas,2021-12-14,2021-12-14,NaN,2.0,NaN,NaN,http://books.google.com/books/content?id=PqVKE...
74728,The Blue Poetry Book Annotated,Standalone Novel,Andrew Lang,NaN,The Blue Poetry Book was the third of the seri...,en,nan - poetry,NaN,NaN,541.0,NaN,2020-04-28,2020-04-28,NaN,NaN,NaN,NaN,NaN
74737,"In Other Words, Love",Standalone Novel,Shirley Jump,NaN,She’s been hired to ghostwrite a CEO’s autobio...,en,Fiction - second chance romance,NaN,NaN,0.0,Hallmark Publishing,2020-04-21,2020-04-21,NaN,NaN,NaN,NaN,http://books.google.com/books/content?id=J1YAE...
74752,Lost in the Dark,Standalone Novel,Brad Weismann,NaN,Two horror films were nominated for the Academ...,en,Performing Arts - zombies horror,NaN,NaN,257.0,Univ. Press of Mississippi,2021-04-22,2021-04-22,NaN,NaN,NaN,NaN,http://books.google.com/books/content?id=snNUD...

In [92]:
df = df.drop_duplicates(subset=['title', 'description', 'author'], keep='first')

In [93]:
duplicados_title_description = df[df.duplicated(subset=['title', 'description'], keep='first')]
duplicados_title_description

,title,series,author,rating,description,language,genres,characters,bookFormat,pages,publisher,publishDate,firstPublishDate,awards,numRatings,likedPercent,setting,coverImg
20619,Cupping Therapy Encyclopedia: New Edition,Standalone Novel,Tamer Shaban (Goodreads Author),5.0,"This book describes the history, methods, and ...",NaN,[] - nan,NaN,Kindle Edition,NaN,NaN,March 24th 2018,NaN,NaN,3.0,100.0,NaN,https://i.gr-assets.com/images/S/compressed.ph...
28025,Out of the Picture and Into the Picture,Standalone Novel,"Victor G. La Van Way (Illustrator), Ilyan Kei ...",4.0,Out of the Picture and Into the Picture by Vic...,English,[] - nan,NaN,ebook,25,Ilyan Kei Lavanway,May 7th 2012,NaN,NaN,4.0,75.0,NaN,https://i.gr-assets.com/images/S/compressed.ph...
31028,Lucid Exposition of the Middle Way: The Essent...,Standalone Novel,Mervyn Sprung,0.0,Originally published in 1979.The Prasannapada ...,en,[] - nan,NaN,ebook,302,Routledge,May 13th 2013,01/01/13,NaN,0.0,NaN,NaN,https://i.gr-assets.com/images/S/compressed.ph...
52491,CyberPunk,Standalone Novel,Cyberpunk House,NaN,"Attention Cyberpunk Army, Looking for a new Ga...",en,nan - cyberpunk,NaN,NaN,120.0,NaN,2020-03-27,2020-03-27,NaN,NaN,NaN,NaN,http://books.google.com/books/content?id=iJDhE...
54934,Love Story of an Introvert Medico,Standalone Novel,Dr. Vaibhav Motghare,5.0,"Every person on this planet, whether introvert...",en,Fiction - introvert romance,NaN,NaN,46.0,Notion Press,2021-07-11,2021-07-11,NaN,4.0,NaN,NaN,http://books.google.com/books/content?id=TMk3E...
56533,Todos Somos Villanos,Standalone Novel,M. L. Rio,NaN,Oliver Marks is released from jail after ten y...,es,Fiction - romcom,NaN,NaN,0.0,Ediciones Urano,2023-06-27,2023-06-27,NaN,NaN,NaN,NaN,http://books.google.com/books/content?id=v5vQE...
58178,"Oh, Great! I was Reincarnated as a Farmer",Standalone Novel,Benjamin Neihana Kerei,5.0,What do you have when you blend a pinch of lit...,en,nan - litRPG,NaN,NaN,618.0,NaN,2021-06-08,2021-06-08,NaN,1.0,NaN,NaN,http://books.google.com/books/content?id=SFSBz...
59520,Superhero Fiction,Standalone Novel,Terry Dolin,NaN,Superhero fiction is a genre of speculative fi...,en,nan - superhero fiction,NaN,NaN,396.0,Independently Published,2021-06-11,2021-06-11,NaN,NaN,NaN,NaN,http://books.google.com/books/content?id=Qfvtz...
60360,Neo Magic,Standalone Novel,"Francisco Villalón López, Sam H Sharpe",NaN,En Neo Magic encontrarás indagaciones sobre la...,es,nan - magical creatures,NaN,NaN,160.0,NaN,2020-03-20,2020-03-20,NaN,NaN,NaN,NaN,http://books.google.com/books/content?id=85Jkz...
60670,CyberPunk,Standalone Novel,Runtill sun,NaN,"Attention Cyberpunk Army, Looking for a new Ga...",en,nan - cyberpunk,NaN,NaN,120.0,NaN,2020-03-15,2020-03-15,NaN,NaN,NaN,NaN,http://books.google.com/books/content?id=iJDhE...
62682,The Portal Guardians,Standalone Novel,Ellie Holland,NaN,In a magical library? ?a young elf studies. Br...,en,nan - portal fantasy,NaN,NaN,414.0,Amalgam Chronicles,2021-12-30,2021-12-30,NaN,NaN,NaN,NaN,http://books.google.com/books/content?id=jM-JC...
63138,Antiheroines of Contemporary Media,Standalone Novel,"Melanie Haas, N. A. Pierce, Gretchen Lynne Busl",NaN,This volume of essays provides a critical fora...,en,Literary Criticism - antiheroes,NaN,NaN,0.0,NaN,2021,2021,NaN,NaN,NaN,NaN,http://books.google.com/books/content?id=xJ9iE...
66307,Iarraindorn,Standalone Novel,Philip Dickens,NaN,"ON THE NIGHT THAT HE WAS BORN, THE DEVIL CAME ...",en,nan - historical fantasy adventure,NaN,NaN,212.0,NaN,2021-05-31,2021-05-31,NaN,NaN,NaN,NaN,http://books.google.com/books/content?id=8M53z...
66784,Multi-Mind Mayhem Volume 7,Standalone Novel,"Ryousen Takami, Honoji Honoji",NaN,"On the orders of King Welkin, Bard has become ...",en,Comics & Graphic Novels - isekai historical,NaN,NaN,208.0,SCB Distributors,2023-04-11,2023-04-11,NaN,NaN,NaN,NaN,http://books.google.com/books/content?id=lcNYz...
67026,The Archer & The Flame,Standalone Novel,MARIE. VIOLET,NaN,"When duty meets desire, which will prevail? Wi...",en,Fiction - fae fantasy,NaN,NaN,0.0,NaN,2024-10-30,2024-10-30,NaN,NaN,NaN,NaN,http://books.google.com/books/content?id=nusCE...
67162,The Wrong Way to Use Healing Magic Volume 1,Standalone Novel,"Kugayama Reki, Kurokata Kurokata",NaN,"Usato, an ordinary high schooler, happens to r...",en,Comics & Graphic Novels - isekai fantasy comedy,NaN,NaN,198.0,SCB Distributors,2022-11-22,2022-11-22,NaN,NaN,NaN,NaN,http://books.google.com/books/content?id=DauJE...
67599,The Death Mage Volume 4,Standalone Novel,Densuke,NaN,The fight with the vampires draws near! Having...,en,nan - isekai dark fantasy,NaN,NaN,0.0,One Peace Books,2024-02-13,2024-02-13,NaN,NaN,NaN,NaN,http://books.google.com/books/content?id=ikDtE...
67802,Multi-Mind Mayhem Volume 3,Standalone Novel,"Ryousen Takami, Honoji, Matt Schley",NaN,Bard Cornelius is no ordinary nobleman's son. ...,en,Comics & Graphic Novels - isekai historical,NaN,NaN,200.0,One Peace Books,2022-04-12,2022-04-12,NaN,NaN,NaN,NaN,http://books.google.com/books/content?id=NZ-az...
68911,Mythical Mermaids - Fantasy Adult Coloring Book,Standalone Novel,Terry Pino,NaN,"A Beautiful Premium cover design, Perfect for ...",en,nan - mermaids fantasy,NaN,NaN,24.0,NaN,2020-07-10,2020-07-10,NaN,NaN,NaN,NaN,http://books.google.com/books/content?id=wP3aj...
68914,Creative Haven Magnificent Mermaids Coloring Book,Standalone Novel,Mermaid Jack,NaN,Sherri Baldy's NEW SUPER Beautiful & Enchantin...,en,nan - mermaids fantasy,NaN,NaN,58.0,Independently Published,2020-08-29,2020-08-29,NaN,NaN,NaN,NaN,http://books.google.com/books/content?id=HzKND...
69009,Creative Haven Magnificent Mermaids Coloring Book,Standalone Novel,Mermaids Momo,NaN,Sherri Baldy's NEW SUPER Beautiful & Enchantin...,en,nan - mermaids fantasy,NaN,NaN,58.0,Independently Published,2020-08-29,2020-08-29,NaN,NaN,NaN,NaN,http://books.google.com/books/content?id=HzKND...
69013,Creative Haven Magnificent Mermaids Coloring Book,Standalone Novel,Mermaids Margret,NaN,Sherri Baldy's NEW SUPER Beautiful & Enchantin...,en,nan - mermaids fantasy,NaN,NaN,58.0,Independently Published,2020-08-29,2020-08-29,NaN,NaN,NaN,NaN,http://books.google.com/books/content?id=HzKND...
69131,Multi-Mind Mayhem Volume 4,Standalone Novel,"Ryousen Takami, Honoji Honoji",NaN,Bard Cornelius is no ordinary nobleman's son. ...,en,Comics & Graphic Novels - isekai drama,NaN,NaN,192.0,SCB Distributors,2022-07-26,2022-07-26,NaN,NaN,NaN,NaN,http://books.google.com/books/content?id=-nKaz...
69242,Mermaid Coloring Book for Adults,Standalone Novel,Rfza,NaN,Dive into an underwater adventure in this beau...,en,Games & Activities - mermaids fantasy,NaN,NaN,122.0,Only1million Incorporated,2020-12-03,2020-12-03,NaN,NaN,NaN,NaN,NaN
69384,Zombie Coloring Book for Kids,Standalone Novel,Zombie Book,NaN,"Unique, Cool, and Fun!8.5""x11"" Glossy Cover Pa...",en,nan - zombies fantasy,NaN,NaN,112.0,NaN,2020-10-17,2020-10-17,NaN,NaN,NaN,NaN,http://books.google.com/books/content?id=Mit2z...
69386,Zombie Coloring Book for Kids,Standalone Novel,Coloring Book,NaN,"Unique, Cool, and Fun!8.5""x11"" Glossy Cover Pa...",en,nan - zombies fantasy,NaN,NaN,112.0,NaN,2020-10-17,2020-10-17,NaN,NaN,NaN,NaN,http://books.google.com/books/content?id=Mit2z...
69387,Zombie Coloring Book for Kids,Standalone Novel,Coloer Book,NaN,"Unique, Cool, and Fun!8.5""x11"" Glossy Cover Pa...",en,nan - zombies fantasy,NaN,NaN,112.0,NaN,2020-10-17,2020-10-17,NaN,NaN,NaN,NaN,http://books.google.com/books/content?id=Mit2z...
69388,Zombie Coloring Book for Kids,Standalone Novel,Coloring Page,NaN,"Unique, Cool, and Fun!8.5""x11"" Glossy Cover Pa...",en,nan - zombies fantasy,NaN,NaN,112.0,Independently Published,2020-10-17,2020-10-17,NaN,NaN,NaN,NaN,http://books.google.com/books/content?id=Mit2z...
69389,Zombie Coloring Book for Kids,Standalone Novel,Color Book,NaN,"Unique, Cool, and Fun!8.5""x11"" Glossy Cover Pa...",en,nan - zombies fantasy,NaN,NaN,112.0,NaN,2020-10-17,2020-10-17,NaN,NaN,NaN,NaN,http://books.google.com/books/content?id=Mit2z...
69391,Zombie Coloring Book for Kids,Standalone Novel,Colouring Book,NaN,"Unique, Cool, and Fun!8.5""x11"" Glossy Cover Pa...",en,nan - zombies fantasy,NaN,NaN,112.0,NaN,2020-10-17,2020-10-17,NaN,NaN,NaN,NaN,http://books.google.com/books/content?id=Mit2z...
69595,Halloween Colouring Book for Kids,Standalone Novel,Colouring Book,NaN,"Unique, Cool, and Fun!8.5""x11"" Glossy Cover Pa...",en,nan - zombies fantasy,NaN,NaN,112.0,Independently Published,2020-10-16,2020-10-16,NaN,NaN,NaN,NaN,http://books.google.com/books/content?id=qjkct...
69596,Hallowen Colouring Book for Kids,Standalone Novel,Coloring Booke,NaN,"Unique, Cool, and Fun!8.5""x11"" Glossy Cover Pa...",en,nan - zombies fantasy,NaN,NaN,112.0,NaN,2020-10-16,2020-10-16,NaN,NaN,NaN,NaN,http://books.google.com/books/content?id=p3H6z...
69711,Hallowen Colouring Book for Kids,Standalone Novel,Coloer Book,NaN,"Unique, Cool, and Fun!8.5""x11"" Glossy Cover Pa...",en,nan - zombies fantasy,NaN,NaN,112.0,NaN,2020-10-16,2020-10-16,NaN,NaN,NaN,NaN,http://books.google.com/books/content?id=p3H6z...
71179,Modes of Composition and the Durability of Sty...,Standalone Novel,David L. Hoover,NaN,Modes of Composition and the Durability of Sty...,en,Literary Criticism - literary fiction horror,NaN,NaN,239.0,Routledge,2020-11-29,2020-11-29,NaN,NaN,NaN,NaN,http://books.google.com/books/content?id=eJb-D...
71568,Zombie Coloring Book for Kids,Standalone Novel,Zombie Coloring,NaN,"Unique, Cool, and Fun!8.5""x11"" Glossy Cover Pa...",en,nan - zombies horror,NaN,NaN,112.0,NaN,2020-10-17,2020-10-17,NaN,NaN,NaN,NaN,http://books.google.com/books/content?id=Mit2z...
71849,Martial Peak Vol 48,Standalone Novel,Ryan AIKA,NaN,"The journey to the martial peak is a lonely, s...",en,nan - shounen romance,NaN,NaN,96.0,NaN,2020-11-06,2020-11-06,NaN,NaN,NaN,NaN,NaN
71853,Battle Through the Heavens Vol 45,Standalone Novel,Patel KINJAL,NaN,"In a land where there is no magic, a land wher...",en,nan - shounen romance,NaN,NaN,83.0,NaN,2020-10-19,2020-10-19,NaN,NaN,NaN,NaN,NaN
72128,Terror Empire Coloring Book For Adults,Standalone Novel,Sweet Lemon Art Co,NaN,BOO! Our Horror coloring book takes you on an ...,en,nan - zombies horror,NaN,NaN,66.0,NaN,2020-12-15,2020-12-15,NaN,NaN,NaN,NaN,http://books.google.com/books/content?id=94RJz...
72135,Hallowen Colouring Book for Kids,Standalone Novel,Coloring Book,NaN,"Unique, Cool, and Fun!8.5""x11"" Glossy Cover Pa...",en,nan - zombies horror,NaN,NaN,112.0,NaN,2020-10-16,2020-10-16,NaN,NaN,NaN,NaN,http://books.google.com/books/content?id=p3H6z...
72399,Fury of Angels,Standalone Novel,Julie Light,NaN,"My oldest friend might just be Lucifer, Angel ...",en,nan - fallen angels fantasy,NaN,NaN,310.0,NaN,2020-11-13,2020-11-13,NaN,NaN,NaN,NaN,http://books.google.com/books/content?id=hKhQB...
72478,Battle Through the Heavens Vol 14,Standalone Novel,Patel KINJAL,NaN,"In a land where there is no magic, a land wher...",en,nan - shounen romance,NaN,NaN,86.0,NaN,2020-10-19,2020-10-19,NaN,NaN,NaN,NaN,NaN
72758,Battle Through the Heavens Vol 11,Standalone Novel,Patel KINJAL,NaN,"In a land where there is no magic, a land wher...",en,nan - shounen romance,NaN,NaN,90.0,NaN,2020-10-19,2020-10-19,NaN,NaN,NaN,NaN,http://books.google.com/books/content?id=T0LSE...
72759,Martial Peak Vol 27,Standalone Novel,Jamie Fields,NaN,"The journey to the martial peak is a lonely, s...",en,nan - shounen romance,NaN,NaN,71.0,NaN,2020-09-10,2020-09-10,NaN,NaN,NaN,NaN,NaN
72760,Martial Peak Vol 27,Standalone Novel,James FREEMAN,NaN,"The journey to the martial peak is a lonely, s...",en,nan - shounen romance,NaN,NaN,71.0,NaN,2020-08-28,2020-08-28,NaN,NaN,NaN,NaN,NaN
72763,Battle Through the Heavens Vol 39,Standalone Novel,Patel KINJAL,NaN,"In a land where there is no magic, a land wher...",en,nan - shounen romance,NaN,NaN,82.0,NaN,2020-10-19,2020-10-19,NaN,NaN,NaN,NaN,NaN
72766,Battle Through the Heavens Vol 17,Standalone Novel,reuben nisenfeld,NaN,"In a land where there is no magic, a land wher...",en,nan - shounen romance,NaN,NaN,85.0,NaN,2020-09-19,2020-09-19,NaN,NaN,NaN,NaN,NaN
72770,Battle Through the Heavens Vol 15,Standalone Novel,Richard CONTRERAS,NaN,"In a land where there is no magic, a land wher...",en,nan - shounen romance,NaN,NaN,83.0,NaN,2020-09,2020-09,NaN,NaN,NaN,NaN,NaN
72772,Battle Through the Heavens Vol 36,Standalone Novel,Patel KINJAL,NaN,"In a land where there is no magic, a land wher...",en,nan - shounen romance,NaN,NaN,81.0,NaN,2020-10-19,2020-10-19,NaN,NaN,NaN,NaN,NaN
72776,Rebirth of the Urban Immortal Cultivator Vol 10,Standalone Novel,Dawood HALA,NaN,"During the anti-cataclysm period, the monk Che...",en,nan - shounen romance,NaN,NaN,75.0,NaN,2020-10-07,2020-10-07,NaN,NaN,NaN,NaN,NaN
72777,Rebirth of the Urban Immortal Cultivator Vol 13,Standalone Novel,Lonny DAUGHERTY,NaN,"During the anti-cataclysm period, the monk Che...",en,nan - shounen romance,NaN,NaN,70.0,NaN,2020-08-31,2020-08-31,NaN,NaN,NaN,NaN,NaN
73523,Star Martial God Technique Chap 4,Standalone Novel,VEGA-RIVERA LUZ,NaN,Killed by a Sage Emperor and reborn as his 13 ...,en,nan - shounen romance,NaN,NaN,77.0,NaN,2020-09-28,2020-09-28,NaN,NaN,NaN,NaN,NaN
73538,Tang Yin's Adventure Vol 24,Standalone Novel,Ortiz Vega MARIA,NaN,"""Tang Yin's Adventure in Another World"" mainly...",en,nan - shounen romance,NaN,NaN,90.0,NaN,2020-10-17,2020-10-17,NaN,NaN,NaN,NaN,NaN
73546,Tang Yin's Adventure Vol 7,Standalone Novel,reuben nisenfeld,NaN,"""Tang Yin's Adventure in Another World"" mainly...",en,nan - shounen romance,NaN,NaN,73.0,NaN,2020-09-18,2020-09-18,NaN,NaN,NaN,NaN,NaN
73554,Tang Yin's Adventure Vol 30,Standalone Novel,reuben nisenfeld,NaN,"""Tang Yin's Adventure in Another World"" mainly...",en,nan - shounen romance,NaN,NaN,73.0,NaN,2020-09-18,2020-09-18,NaN,NaN,NaN,NaN,NaN
73560,Tables of Demons and God Chap 45,Standalone Novel,Noah Nguyen,NaN,Killed by a Sage Emperor and reborn as his 13 ...,en,nan - shounen romance,NaN,NaN,78.0,NaN,2020-04-03,2020-04-03,NaN,NaN,NaN,NaN,http://books.google.com/books/content?id=t1mVz...
73678,Sexy Anime Girls Coloring Book,Standalone Novel,World Of Coloring,NaN,"Do you love Anime? If your answer is yes, Let'...",en,nan - yuri fantasy,NaN,NaN,72.0,NaN,2020-11-04,2020-11-04,NaN,NaN,NaN,NaN,NaN
73683,Sexy Anime Milf Coloring Book,Standalone Novel,Activity Coloring Art,NaN,"Do you love Anime? If your answer is yes, Let'...",en,nan - yuri fantasy,NaN,NaN,81.0,NaN,2021-06-06,2021-06-06,NaN,NaN,NaN,NaN,http://books.google.com/books/content?id=YsfAz...
73684,Sexy Anime Girls Coloring Book,Standalone Novel,Funny Art,NaN,"Do you love Anime? If your answer is yes, Let'...",en,nan - yuri fantasy,NaN,NaN,70.0,NaN,2021-09-05,2021-09-05,NaN,NaN,NaN,NaN,NaN
74344,Journey To Find The Truth,Standalone Novel,Delmar Coldwell,NaN,When Ray is asked to investigate Crow's Cottag...,en,nan - occult thriller,NaN,NaN,232.0,NaN,2021-01-12,2021-01-12,NaN,NaN,NaN,NaN,http://books.google.com/books/content?id=EvVmB...

In [94]:
df = df.drop_duplicates(subset=['title', 'description'], keep='first')

In [95]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 70843 entries, 0 to 74788
Data columns (total 18 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   title             70843 non-null  object
 1   series            70843 non-null  object
 2   author            70843 non-null  object
 3   rating            52710 non-null  float64
 4   description       70843 non-null  object
 5   language          69706 non-null  object
 6   genres            70843 non-null  object
 7   characters        13733 non-null  object
 8   bookFormat        50291 non-null  object
 9   pages             69561 non-null  object
 10  publisher         65346 non-null  object
 11  publishDate       70558 non-null  object
 12  firstPublishDate  50104 non-null  object
 13  awards            10589 non-null  object
 14  numRatings        52710 non-null  float64
 15  likedPercent      51018 non-null  float64
 16  setting           11533 non-null  object
 17  coverImg          68762 non-null  object
dtypes: float64(3), object(15)
memory usage: 10.3+ MB

# language

In [96]:
df['language'].unique()

array(['English', 'French', 'German', 'Persian', 'Arabic', nan, 'en',
       'Spanish', 'Multiple languages', 'Portuguese', 'Indonesian',
       'Turkish', 'Polish', 'Bulgarian', 'Tamil', 'Japanese', 'Romanian',
       'Italian', 'French, Middle (ca.1400-1600)', 'Norwegian', 'Urdu',
       'Dutch', 'de', 'Finnish', 'Marathi', 'Chinese', 'Swedish',
       'Icelandic', 'Malayalam', 'ar', 'Croatian', 'Estonian',
       'Greek, Modern (1453-)', 'Russian', 'no', 'fa', 'fr', 'Kurdish',
       'Danish', 'Hindi', 'ro', 'Filipino; Pilipino', 'Serbian',
       'Bengali', 'Malay', 'Catalan; Valencian', 'Czech', 'Vietnamese',
       'pt-BR', 'Armenian', 'Georgian', 'Kannada', 'Korean', 'sv',
       'Nepali', 'Telugu', 'Hungarian', 'English, Middle (1100-1500)',
       'Farsi', 'Lithuanian', 'Ukrainian',
       'Bokmål, Norwegian; Norwegian Bokmål', 'Slovak', 'ja', 'es',
       'Faroese', 'Basque', 'id', 'Macedonian', 'Maltese', 'pl',
       'Amharic', 'gu', 'tr', 'nl', 'bg', 'ms', 'Assamese', 'Gujarati',
       'Panjabi; Punjabi', 'zh-CN', 'Albanian', 'Latvian', 'Bosnian',
       'vi', 'fi', 'Thai', 'lt', 'sq', 'it',
       'Dutch, Middle (ca.1050-1350)', 'Mongolian', 'Tagalog', 'hu', 'cs',
       'Galician', 'tl', 'da', 'Aleut', 'Slovenian', 'Undetermined',
       'Greek, Ancient (to 1453)', 'Mayan languages', 'ca', 'Duala',
       'Australian languages', 'ru',
       'Norwegian Nynorsk; Nynorsk, Norwegian', 'Afrikaans', 'ko', 'gl',
       'un'], dtype=object)

Ponemos todos los idiomas en el mismo formato

In [97]:
language_map = {
    'english': 'en',
    'english, middle (1100-1500)': 'en',
    'french': 'fr',
    'french, middle (ca.1400-1600)': 'fr',
    'german': 'de',
    'de': 'de',
    'persian': 'fa',
    'farsi': 'fa',
    'fa': 'fa',
    'arabic': 'ar',
    'ar': 'ar',
    'spanish': 'es',
    'es': 'es',
    'multiple languages': 'mul',
    'portuguese': 'pt',
    'pt-br': 'pt',
    'italian': 'it',
    'it': 'it',
    'romanian': 'ro',
    'ro': 'ro',
    'turkish': 'tr',
    'tr': 'tr',
    'polish': 'pl',
    'pl': 'pl',
    'bulgarian': 'bg',
    'bg': 'bg',
    'tamil': 'ta',
    'ta': 'ta',
    'japanese': 'ja',
    'ja': 'ja',
    'norwegian': 'no',
    'bokmål, norwegian; norwegian bokmål': 'no',
    'norwegian nynorsk; nynorsk, norwegian': 'no',
    'no': 'no',
    'urdu': 'ur',
    'dutch': 'nl',
    'dutch, middle (ca.1050-1350)': 'nl',
    'nl': 'nl',
    'finnish': 'fi',
    'fi': 'fi',
    'marathi': 'mr',
    'chinese': 'zh',
    'zh-cn': 'zh',
    'swedish': 'sv',
    'sv': 'sv',
    'icelandic': 'is',
    'malayalam': 'ml',
    'croatian': 'hr',
    'estonian': 'et',
    'greek, modern (1453-)': 'el',
    'greek, ancient (to 1453)': 'grc',
    'russian': 'ru',
    'ru': 'ru',
    'kurdish': 'ku',
    'danish': 'da',
    'da': 'da',
    'hindi': 'hi',
    'filipino; pilipino': 'tl',
    'tagalog': 'tl',
    'tl': 'tl',
    'serbian': 'sr',
    'sr': 'sr',
    'bengali': 'bn',
    'malay': 'ms',
    'ms': 'ms',
    'catalan; valencian': 'ca',
    'ca': 'ca',
    'czech': 'cs',
    'cs': 'cs',
    'vietnamese': 'vi',
    'vi': 'vi',
    'armenian': 'hy',
    'georgian': 'ka',
    'kannada': 'kn',
    'korean': 'ko',
    'ko': 'ko',
    'nepali': 'ne',
    'slovak': 'sk',
    'telugu': 'te',
    'hungarian': 'hu',
    'hu': 'hu',
    'azerbaijani': 'az',
    'lithuanian': 'lt',
    'lt': 'lt',
    'ukrainian': 'uk',
    'iranian (other)': 'fa',
    'faroese': 'fo',
    'basque': 'eu',
    'indonesian': 'id',
    'id': 'id',
    'macedonian': 'mk',
    'maltese': 'mt',
    'gujarati': 'gu',
    'gu': 'gu',
    'amharic': 'am',
    'sq': 'sq',
    'assamese': 'as',
    'panjabi; punjabi': 'pa',
    'albanian': 'sq',
    'latvian': 'lv',
    'bosnian': 'bs',
    'thai': 'th',
    'th': 'th',
    'afrikaans': 'af',
    'mongolian': 'mn',
    'galician': 'gl',
    'gl': 'gl',
    'slovenian': 'sl',
    'sl': 'sl',
    'aromanian; arumanian; macedo-romanian': 'rup',
    'may languages': 'myn',
    'australian languages': 'aus',
    'duala': 'dua',
    'aleut': 'ale',
    'un': 'und',
    'undetermined': 'und'
}

def normalizar_idioma(valor):
    if pd.isna(valor):
        return None
    clave = str(valor).strip().lower()
    return language_map.get(clave, 'und')  
df['language'] = df['language'].apply(normalizar_idioma)

In [98]:
#los valores nulos los pasamos a 'und' también
df['language'].fillna('und', inplace=True)

# BookFormat

In [99]:
df['bookFormat'].value_counts()

bookFormat
Paperback                26406
Hardcover                12068
Kindle Edition            5767
Mass Market Paperback     2549
ebook                     2525
                         ...
Paperback, eBook             1
paper book                   1
Bonded Leather               1
ebook and paperback          1
pamphlet                     1
Name: count, Length: 132, dtype: int64

In [100]:
#los nulos lo cambiamos a Paperback (tapa blanda) para cambiarlo por la media
df['bookFormat'].fillna("Paperback", inplace=True)

In [101]:
df['bookFormat'].value_counts()

bookFormat
Paperback                46958
Hardcover                12068
Kindle Edition            5767
Mass Market Paperback     2549
ebook                     2525
                         ...
Paperback, eBook             1
paper book                   1
Bonded Leather               1
ebook and paperback          1
pamphlet                     1
Name: count, Length: 132, dtype: int64

# Pages

In [102]:
df['pages'].value_counts()

pages
0.0       1560
0.0       1485
320       1053
352        890
288        870
          ...
2554.0       1
1580.0       1
2060.0       1
856.0        1
633.0        1
Name: count, Length: 3293, dtype: int64

Vamos a eliminar las filas con valores nulos y valores = 0 y convertimos la columna a enteros para que tengan el mismo formato

In [103]:
df = df[df['pages'].notna()]
df['pages'] = df['pages'].astype(str)
df['pages'] = df['pages'].str.extract('(\d+)')
df = df[df['pages'].notna()]
df['pages'] = df['pages'].astype(int)
df = df[df['pages'] != 0]

In [104]:
df['pages'].value_counts()

pages
320      1108
352       957
288       922
304       853
256       843
         ...
1640        1
11095       1
1203        1
1286        1
1266        1
Name: count, Length: 1553, dtype: int64

In [105]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 66237 entries, 0 to 74788
Data columns (total 18 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   title             66237 non-null  object
 1   series            66237 non-null  object
 2   author            66237 non-null  object
 3   rating            51133 non-null  float64
 4   description       66237 non-null  object
 5   language          66237 non-null  object
 6   genres            66237 non-null  object
 7   characters        13613 non-null  object
 8   bookFormat        66237 non-null  object
 9   pages             66237 non-null  int32
 10  publisher         62126 non-null  object
 11  publishDate       66091 non-null  object
 12  firstPublishDate  46266 non-null  object
 13  awards            10536 non-null  object
 14  numRatings        51133 non-null  float64
 15  likedPercent      49672 non-null  float64
 16  setting           11454 non-null  object
 17  coverImg          64517 non-null  object
dtypes: float64(3), int32(1), object(14)
memory usage: 9.3+ MB

# Publisher

Miramos los nulos

In [106]:
df['publisher'].isna().sum()

4111

In [107]:
df = df[df['publisher'].notna()]

In [108]:
df['publisher'].value_counts()

publisher
HarperCollins                                  640
Vintage                                        576
Createspace Independent Publishing Platform    446
Penguin Books                                  426
Ballantine Books                               397
                                              ...
Mullen Press                                     1
Phal Publishing                                  1
Yellow Kite                                      1
Battered Suitcase Press                          1
Wildflower Isle                                  1
Name: count, Length: 12851, dtype: int64

# publishDate

In [109]:
df['publishDate'].isna().sum()

3

In [110]:
df['publishDate'] = pd.to_datetime(df['publishDate'], errors='coerce')

C:\Users\elena\AppData\Local\Temp\ipykernel_28456\171273950.py:1: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  df['publishDate'] = pd.to_datetime(df['publishDate'], errors='coerce')
C:\Users\elena\AppData\Local\Temp\ipykernel_28456\171273950.py:1: FutureWarning: In a future version of pandas, parsing datetimes with mixed time zones will raise an error unless `utc=True`. Please specify `utc=True` to opt in to the new behaviour and silence this warning. To create a `Series` with mixed offsets and `object` dtype, please use `apply` and `datetime.datetime.strptime`
  df['publishDate'] = pd.to_datetime(df['publishDate'], errors='coerce')

In [111]:
df = df[df['publishDate'].notna()]

Las guardamos con el mismo fomato

In [112]:
df['publishDate'].apply(type).value_counts()

publishDate
<class 'datetime.datetime'>    61568
Name: count, dtype: int64

# firstPublishDate

In [113]:
df['firstPublishDate'].isna().sum()

18325

Cambiamos la columna por booleanos para saber si ha habido o no otra edicion

In [114]:
df['firstPublishDate'] = df['firstPublishDate'].notna()

# Awards

Cambiamos la columna por booleanos para saber si ha sido premiado o no

In [115]:
df['awards'] = df['awards'].notna()

In [116]:
df

,title,series,author,rating,description,language,genres,characters,bookFormat,pages,publisher,publishDate,firstPublishDate,awards,numRatings,likedPercent,setting,coverImg
0,The Hunger Games,The Hunger Games #1,Suzanne Collins,4.33,WINNING MEANS FAME AND FORTUNE.LOSING MEANS CE...,en,"['Young Adult', 'Fiction', 'Dystopia', 'Fantas...","['Katniss Everdeen', 'Peeta Mellark', 'Cato (H...",Hardcover,374,Scholastic Press,2008-09-14 00:00:00,False,True,6376780.0,96.0,"['District 12, Panem', 'Capitol, Panem', 'Pane...",https://i.gr-assets.com/images/S/compressed.ph...
1,Harry Potter and the Order of the Phoenix,Harry Potter #5,"J.K. Rowling, Mary GrandPré (Illustrator)",4.50,There is a door at the end of a silent corrido...,en,"['Fantasy', 'Young Adult', 'Fiction', 'Magic',...","['Sirius Black', 'Draco Malfoy', 'Ron Weasley'...",Paperback,870,Scholastic Inc.,2004-09-28 00:00:00,True,True,2507623.0,98.0,['Hogwarts School of Witchcraft and Wizardry (...,https://i.gr-assets.com/images/S/compressed.ph...
2,To Kill a Mockingbird,To Kill a Mockingbird,Harper Lee,4.28,The unforgettable novel of a childhood in a sl...,en,"['Classics', 'Fiction', 'Historical Fiction', ...","['Scout Finch', 'Atticus Finch', 'Jem Finch', ...",Paperback,324,Harper Perennial Modern Classics,2006-05-23 00:00:00,True,True,4501075.0,95.0,"['Maycomb, Alabama (United States)']",https://i.gr-assets.com/images/S/compressed.ph...
3,Pride and Prejudice,Standalone Novel,"Jane Austen, Anna Quindlen (Introduction)",4.26,Alternate cover edition of ISBN 9780679783268S...,en,"['Classics', 'Fiction', 'Romance', 'Historical...","['Mr. Bennet', 'Mrs. Bennet', 'Jane Bennet', '...",Paperback,279,Modern Library,2000-10-10 00:00:00,True,False,2998241.0,94.0,"['United Kingdom', 'Derbyshire, England (Unite...",https://i.gr-assets.com/images/S/compressed.ph...
4,Twilight,The Twilight Saga #1,Stephenie Meyer,3.60,About three things I was absolutely positive.\...,en,"['Young Adult', 'Fantasy', 'Romance', 'Vampire...","['Edward Cullen', 'Jacob Black', 'Laurent', 'R...",Paperback,501,"Little, Brown and Company",2006-09-06 00:00:00,True,True,4964519.0,78.0,"['Forks, Washington (United States)', 'Phoenix...",https://i.gr-assets.com/images/S/compressed.ph...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
74779,Beasts & Behemoths (Dungeons & Dragons),Standalone Novel,"Jim Zub, Stacy King, Andrew Wheeler, Official ...",NaN,Study this guide and keep it close at hand--th...,und,Juvenile Nonfiction - dragons romance,NaN,Paperback,114,Ten Speed Press,2020-10-20 00:00:00,True,False,NaN,NaN,NaN,http://books.google.com/books/content?id=1toui...
74780,Faculty of Dragon Riders,Standalone Novel,Dmitry Nazarov,NaN,I tamed the Black Dragon!So I thought until I ...,und,Fiction - dragons romance,NaN,Paperback,401,Litres,2022-08-24 00:00:00,True,False,NaN,NaN,NaN,http://books.google.com/books/content?id=QSGFE...
74786,Midnight Delivery Sex,Standalone Novel,Neneko Narazaki,NaN,Mit SNS-Card zum Sammeln in der ersten Auflage...,de,Comics & Graphic Novels - yaoi,NaN,Paperback,29,Hayabusa,2021-05-04 00:00:00,True,False,NaN,NaN,NaN,http://books.google.com/books/content?id=s_8_E...
74787,Monster Girl: 2,Standalone Novel,Kazuki Funatsu,NaN,"Dopo il loro incontro, Yatsuki si ritrova ad a...",it,Comics & Graphic Novels - isekai comedy,NaN,Paperback,216,Edizioni BD,2020-05-01 00:00:00,True,False,NaN,NaN,NaN,http://books.google.com/books/content?id=_yjnE...
74788,La saison du soleil,Standalone Novel,Shintaro Ishihara,NaN,"Lauréat du prestigieux prix Akutagawa en 1955,...",und,Literary Collections - isekai space opera,NaN,Paperback,131,Belfond,2022-01-27 00:00:00,True,False,NaN,NaN,NaN,http://books.google.com/books/content?id=bjZVE...

# coverImg

In [118]:
df['coverImg'].isna().sum()

1203

Elimianmos las filas con valores nulos

In [119]:
df = df[df['coverImg'].notna()]

# numRatings, likedPercent, setting, characters

Se borran porque faltan muchois datos

In [120]:
df.drop(columns=['numRatings', 'likedPercent', 'setting', 'characters'], inplace=True)

C:\Users\elena\AppData\Local\Temp\ipykernel_28456\3847056173.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df.drop(columns=['numRatings', 'likedPercent', 'setting', 'characters'], inplace=True)

In [121]:
df

,title,series,author,rating,description,language,genres,bookFormat,pages,publisher,publishDate,firstPublishDate,awards,coverImg
0,The Hunger Games,The Hunger Games #1,Suzanne Collins,4.33,WINNING MEANS FAME AND FORTUNE.LOSING MEANS CE...,en,"['Young Adult', 'Fiction', 'Dystopia', 'Fantas...",Hardcover,374,Scholastic Press,2008-09-14 00:00:00,False,True,https://i.gr-assets.com/images/S/compressed.ph...
1,Harry Potter and the Order of the Phoenix,Harry Potter #5,"J.K. Rowling, Mary GrandPré (Illustrator)",4.50,There is a door at the end of a silent corrido...,en,"['Fantasy', 'Young Adult', 'Fiction', 'Magic',...",Paperback,870,Scholastic Inc.,2004-09-28 00:00:00,True,True,https://i.gr-assets.com/images/S/compressed.ph...
2,To Kill a Mockingbird,To Kill a Mockingbird,Harper Lee,4.28,The unforgettable novel of a childhood in a sl...,en,"['Classics', 'Fiction', 'Historical Fiction', ...",Paperback,324,Harper Perennial Modern Classics,2006-05-23 00:00:00,True,True,https://i.gr-assets.com/images/S/compressed.ph...
3,Pride and Prejudice,Standalone Novel,"Jane Austen, Anna Quindlen (Introduction)",4.26,Alternate cover edition of ISBN 9780679783268S...,en,"['Classics', 'Fiction', 'Romance', 'Historical...",Paperback,279,Modern Library,2000-10-10 00:00:00,True,False,https://i.gr-assets.com/images/S/compressed.ph...
4,Twilight,The Twilight Saga #1,Stephenie Meyer,3.60,About three things I was absolutely positive.\...,en,"['Young Adult', 'Fantasy', 'Romance', 'Vampire...",Paperback,501,"Little, Brown and Company",2006-09-06 00:00:00,True,True,https://i.gr-assets.com/images/S/compressed.ph...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
74779,Beasts & Behemoths (Dungeons & Dragons),Standalone Novel,"Jim Zub, Stacy King, Andrew Wheeler, Official ...",NaN,Study this guide and keep it close at hand--th...,und,Juvenile Nonfiction - dragons romance,Paperback,114,Ten Speed Press,2020-10-20 00:00:00,True,False,http://books.google.com/books/content?id=1toui...
74780,Faculty of Dragon Riders,Standalone Novel,Dmitry Nazarov,NaN,I tamed the Black Dragon!So I thought until I ...,und,Fiction - dragons romance,Paperback,401,Litres,2022-08-24 00:00:00,True,False,http://books.google.com/books/content?id=QSGFE...
74786,Midnight Delivery Sex,Standalone Novel,Neneko Narazaki,NaN,Mit SNS-Card zum Sammeln in der ersten Auflage...,de,Comics & Graphic Novels - yaoi,Paperback,29,Hayabusa,2021-05-04 00:00:00,True,False,http://books.google.com/books/content?id=s_8_E...
74787,Monster Girl: 2,Standalone Novel,Kazuki Funatsu,NaN,"Dopo il loro incontro, Yatsuki si ritrova ad a...",it,Comics & Graphic Novels - isekai comedy,Paperback,216,Edizioni BD,2020-05-01 00:00:00,True,False,http://books.google.com/books/content?id=_yjnE...
74788,La saison du soleil,Standalone Novel,Shintaro Ishihara,NaN,"Lauréat du prestigieux prix Akutagawa en 1955,...",und,Literary Collections - isekai space opera,Paperback,131,Belfond,2022-01-27 00:00:00,True,False,http://books.google.com/books/content?id=bjZVE...

Faltaría por hacer la columna de rating y genres

Faltaria hacer one hot encoding y pasarlo todo a numérico